print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/saja/Desktop/NEWLandfill/NewLandfill_A4/Assets/STUVW.mb"`)
{		
	file -o "/Users/saja/Desktop/NEWLandfill/NewLandfill_A4/Assets/STUVW.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/saja/Desktop/NEWLandfill/NewLandfill_A4/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/saja/Desktop/NEWLandfill/NewLandfill_A4/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/saja/Desktop/NEWLandfill/NewLandfill_A4/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
